const app=document.querySelector('#app'),orb=document.querySelector('#orb'),primary=document.querySelector('#orb-primary'),secondary=document.querySelector('#orb-secondary'),panel=document.querySelector('#calendar-panel'),grid=document.querySelector('#calendar-grid'),week=document.querySelector('#calendar-week'),yearEl=document.querySelector('#year-label'),monthEl=document.querySelector('#month-label'),info=document.querySelector('#selected-lunar');
const TZ='Asia/Shanghai', names=['一','二','三','四','五','六','日'];
const holidays=[['中秋节','2026-09-25','2026-09-27'],['国庆节','2026-10-01','2026-10-07']];
let timer=null,holidayMode=false,open=false,y,m,selected='';
const pad=n=>String(n).padStart(2,'0');
function parts(d=new Date()){let a=Object.fromEntries(new Intl.DateTimeFormat('zh-CN',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(d).map(x=>[x.type,x.value]));return Object.fromEntries(['year','month','day','hour','minute','second'].map(k=>[k,+a[k]]));}
function ms(s){return Date.parse(s+'T00:00:00+08:00')}
function cd(x){let t=Math.max(0,Math.floor(x/1000)),d=Math.floor(t/86400),h=Math.floor(t%86400/3600),m=Math.floor(t%3600/60),s=t%60;return d?pad(d)+'d '+pad(h)+'h':pad(h)+':'+pad(m)+':'+pad(s)}
function nextHoliday(){let n=Date.now();return holidays.map(x=>({...x,a:ms(x[1])})).find(x=>x.a>n)||holidays[0]}
function update(){let n=new Date(),p=parts(n);if(!app.classList.contains('hovering')){primary.textContent=pad(p.hour)+':'+pad(p.minute);secondary.textContent='北京时间';return}if(holidayMode){let h=nextHoliday();primary.textContent=cd(h.a-n);secondary.textContent=h[0]}else{let target=Date.UTC(p.year,p.month-1,p.day+(p.hour>=18?1:0),10);primary.textContent=cd(target-n);secondary.textContent='距 18:00'}}
orb.onmouseenter=()=>{if(open)return;app.classList.add('hovering');holidayMode=false;clearTimeout(timer);timer=setTimeout(()=>{holidayMode=true;app.classList.add('holiday-mode');update()},3000);update()};
orb.onmouseleave=()=>{clearTimeout(timer);app.classList.remove('hovering','holiday-mode');holidayMode=false;update()};
orb.onclick=()=>open?close():openCal();
function openCal(){open=true;let p=parts();y=p.year;m=p.month-1;selected=y+'-'+pad(m+1)+'-'+pad(p.day);app.classList.add('expanded');render();floatingClock?.setExpanded?.(true)}
function close(){open=false;app.classList.remove('expanded');floatingClock?.setExpanded?.(false);update()}
function lunar(d){try{let z=new Intl.DateTimeFormat('zh-CN-u-ca-chinese',{timeZone:TZ,month:'long',day:'numeric'}).formatToParts(d),mo=z.find(x=>x.type==='month')?.value||'',da=z.find(x=>x.type==='day')?.value||'';return mo+da}catch{return '农历'}}
function render(){yearEl.textContent=y+'年';monthEl.textContent=(m+1)+'月';week.innerHTML=names.map(x=>'<div class="weekday">'+x+'</div>').join('');let first=new Date(Date.UTC(y,m,1)),start=(first.getUTCDay()+6)%7,count=new Date(Date.UTC(y,m+1,0)).getUTCDate(),total=Math.ceil((start+count)/7)*7,h='';for(let i=0;i<total;i++){let d=i-start+1,yy=y,mm=m;if(d<1){mm--;if(mm<0){mm=11;yy--}d=new Date(Date.UTC(yy,mm+1,0)).getUTCDate()+d}else if(d>count){mm++;if(mm>11){mm=0;yy++}d-=count}let key=yy+'-'+pad(mm+1)+'-'+pad(d),muted=mm!==m,hol=holidays.some(q=>ms(key)>=ms(q[1])&&ms(key)<=ms(q[2])),today=parts();let isToday=yy===today.year&&mm===today.month-1&&d===today.day;h+=`<button class="day ${muted?'muted':''} ${isToday?'today':''} ${key===selected?'selected':''} ${hol?'day-holiday':''}" data-date="${key}"><span class="day-inner"><span class="day-face">${d}</span><span class="day-face lunar-face"><span class="lunar-num">${lunar(new Date(Date.UTC(yy,mm,d,4)))}</span></span></span></button>`}grid.innerHTML=h;grid.querySelectorAll('.day').forEach(b=>b.onclick=()=>{selected=b.dataset.date;b.classList.toggle('flipped');grid.querySelectorAll('.day').forEach(x=>x!==b&&x.classList.remove('selected'));b.classList.add('selected');info.textContent=b.dataset.date+' · '+lunar(new Date(b.dataset.date+'T04:00:00+08:00'))})}
document.querySelector('#prev-month').onclick=e=>{e.stopPropagation();if(--m<0){m=11;y--}render()};document.querySelector('#next-month').onclick=e=>{e.stopPropagation();if(++m>11){m=0;y++}render()};panel.onmouseleave=()=>{if(open)close()};setInterval(update,250);update();